# Generated by Django 2.1.2 on 2018-10-24 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinephilia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('genre', models.CharField(max_length=400)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='cinephilia',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='date_rls.Movie'),
        ),
        migrations.AddField(
            model_name='cinephilia',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
