# Generated by Django 2.1.2 on 2018-10-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('date_rls', '0004_auto_20181024_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinephilia',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermovie',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cinephilia',
        ),
    ]
