# Generated by Django 2.1.2 on 2018-10-26 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('date_rls', '0008_usermovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovie',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='usermovie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='usermovies',
            field=models.ManyToManyField(related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserMovie',
        ),
    ]
