# Generated by Django 2.1.2 on 2018-10-28 21:30

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('date_rls', '0009_auto_20181026_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='posters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='usermovies',
            field=models.ManyToManyField(blank=True, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
